//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDental.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int citaid { get; set; }
        public int pacienteid { get; set; }
        public System.TimeSpan hora { get; set; }
        public int dentistaid { get; set; }
        public int motivoid { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual dentista dentista { get; set; }
    }
}
