//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDental.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbconsultorioEntities1 : DbContext
    {
        

        public dbconsultorioEntities1()
            : base("name=dbconsultorioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<motivo> motivoes { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<dentista> dentistas { get; set; }
    
        public virtual int calculotiemporestante(Nullable<int> id, ObjectParameter diasrestantes, ObjectParameter horasrestantes, ObjectParameter estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("calculotiemporestante", idParameter, diasrestantes, horasrestantes, estado);
        }
    
        public virtual ObjectResult<ObtenerCitas_Result> ObtenerCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCitas_Result>("ObtenerCitas");
        }
    
        public virtual ObjectResult<procesarcitas_Result> procesarcitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procesarcitas_Result>("procesarcitas");
        }
    }
}
